[package]
name = "event-driven-library"
version = "0.1.33"
edition = "2021"
license = "MIT"
description = "Rust Library For Event Driven Message Handling"
repository = "https://github.com/BeringLab/event-driven-library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
event-driven-core= {version="0.1.14", path="./event-driven-core"}
event-driven-macro= {version="0.1.13", path="./event-driven-macro"}
static_assertions="1.1.0"
