[package]
name = "event-driven-library"
version = "0.1.4"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
description = "Rust Library For Event Driven Message Handling"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync"] }
downcast-rs ="1"
serde = {version="1",features=["derive"]}
serde_json = "1"
uuid = { version = "1.3.3", features = ["v4"]}
chrono = {version="0.4"}
async-trait = {version="0.1"}
futures="0.3"
macro_rules_attribute="0.2"

