[package]
name = "event-driven-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
event-driven-core = {version="0.1.0", path="../event-driven-core"}
syn = {version="*", fetures=["extra-traits","derive","full"]}
quote = "*"
proc-macro2="*"